apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustapi
spec:
  template:
    spec:
      containers:
      - name: rustapi
        env:
        - name: ENVIRONMENT
          value: "staging"

